# Generated by Django 2.1.7 on 2019-04-08 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cover_page', '0003_my_favourite'),
    ]

    operations = [
        migrations.CreateModel(
            name='Search_product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.TextField()),
                ('product_link', models.TextField()),
                ('product_image_link', models.TextField()),
                ('product_name', models.TextField()),
                ('product_price', models.TextField()),
                ('selling_website', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='my_favourite',
            name='product_image_link',
        ),
        migrations.RemoveField(
            model_name='my_favourite',
            name='product_tag',
        ),
    ]
