# Generated by Django 2.1.7 on 2019-04-08 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cover_page', '0004_auto_20190408_1943'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='my_favourite',
            table='User_Favourite',
        ),
    ]
