# Generated by Django 2.1.7 on 2019-04-25 15:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cover_page', '0005_auto_20190409_0740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='my_favourite',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
